"use client";
import { apiFetch } from '@/lib/api';

import { useEffect, useState } from 'react';
import { 
  FileText, Download, Eye, Plus, Sparkles, Loader2, AlertCircle, FileBarChart, CheckCircle2, TrendingUp, TrendingDown
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { format } from "date-fns";

export default function ReportsDashboard() {
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const res = await apiFetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/reports/monthly`);
      if (!res.ok) throw new Error("Failed to load reports");
      const json = await res.json();
      setReports(json);
    } catch (error: any) {
      toast.error(error.message);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = async () => {
    try {
      setGenerating(true);
      // Hardcode hospital 2 (South PHC) for prototype demonstration
      toast.info("Generating AI Report... This may take a moment.");
      const res = await apiFetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/reports/generate`, {
        method: "POST"
      });
      if (!res.ok) throw new Error("Failed to generate report");
      const data = await res.json();
      toast.success("Professional AI Report generated successfully!");
      fetchReports();
    } catch (error: any) {
      toast.error(error.message);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="flex flex-col gap-6 max-w-7xl mx-auto pb-10">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h2 className="text-3xl font-bold text-foreground">Monthly AI Reports</h2>
          <p className="text-sm text-muted-foreground mt-1 font-medium">
            Executive operational audit reports generated by Gemini.
          </p>
        </div>
        <div className="flex gap-2">
          <Button 
            className="gap-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-full font-semibold px-6 shadow-md transition-transform active:scale-95"
            onClick={handleGenerateReport}
            disabled={generating}
          >
            {generating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4" />
            )}
            {generating ? "Generating PDF..." : "Generate AI Report"}
          </Button>
        </div>
      </div>

      {/* Overview Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-2">
        <Card className="bg-card border-border shadow-sm">
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-1">Total Reports</p>
              <div className="flex items-baseline gap-2">
                <p className="text-3xl font-black text-foreground">{reports.length}</p>
              </div>
            </div>
            <div className="w-12 h-12 rounded-full bg-blue-100 flex items-center justify-center">
              <FileBarChart className="w-6 h-6 text-blue-600" />
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-card border-border shadow-sm">
          <CardContent className="p-5 flex items-center justify-between">
            <div>
              <p className="text-xs font-bold text-muted-foreground uppercase tracking-wider mb-1">Critical Hospitals</p>
              <div className="flex items-baseline gap-2">
                <p className="text-3xl font-black text-red-600">
                  {reports.filter(r => r.risk_level === 'Critical').length}
                </p>
              </div>
            </div>
            <div className="w-12 h-12 rounded-full bg-red-100 flex items-center justify-center">
              <AlertCircle className="w-6 h-6 text-red-600" />
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-br from-indigo-600 to-blue-700 text-white shadow-md lg:col-span-2">
          <CardContent className="p-5 h-full flex flex-col justify-center">
             <div className="flex items-center gap-2 mb-2">
                <Sparkles className="w-5 h-5 text-indigo-200" />
                <p className="text-xs font-bold text-indigo-100 uppercase tracking-wider">District AI Summary</p>
             </div>
             <p className="text-sm font-medium leading-relaxed opacity-90">
               Based on the latest reports, district health is stable. However, localized medicine shortages at South PHC require immediate administrative attention to prevent critical out-of-stock events next month.
             </p>
          </CardContent>
        </Card>
      </div>

      {/* Reports Table */}
      <Card className="border-border shadow-sm mt-2">
        <CardHeader className="pb-3 border-b border-border/50">
          <CardTitle className="text-base font-bold text-foreground">Generated Reports Archive</CardTitle>
        </CardHeader>
        <div className="overflow-x-auto">
          {loading ? (
            <div className="flex items-center justify-center p-10">
              <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
            </div>
          ) : reports.length === 0 ? (
            <div className="flex flex-col items-center justify-center p-10 text-muted-foreground">
              <FileText className="w-12 h-12 mb-4 opacity-20" />
              <p className="font-medium">No reports generated yet.</p>
              <p className="text-sm">Click "Generate AI Report" to create your first monthly report.</p>
            </div>
          ) : (
            <table className="w-full text-sm text-left whitespace-nowrap">
              <thead className="text-xs text-muted-foreground uppercase bg-muted/50 border-b border-border/50">
                <tr>
                  <th className="px-6 py-4 font-semibold">Hospital Name</th>
                  <th className="px-6 py-4 font-semibold">Report Month</th>
                  <th className="px-6 py-4 font-semibold">Health Score</th>
                  <th className="px-6 py-4 font-semibold">Risk Level</th>
                  <th className="px-6 py-4 font-semibold">Generated On</th>
                  <th className="px-6 py-4 font-semibold text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/50">
                {reports.map((report) => (
                  <tr key={report.id} className="hover:bg-muted/30 transition-colors">
                    <td className="px-6 py-4 font-bold text-foreground">
                      {report.hospital_name}
                    </td>
                    <td className="px-6 py-4 font-medium">
                      {report.report_month}
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <span className={`font-black text-lg ${report.health_score > 75 ? 'text-green-600' : report.health_score > 50 ? 'text-yellow-600' : 'text-red-600'}`}>
                          {report.health_score}
                        </span>
                        {report.health_score > 70 ? (
                          <TrendingUp className="w-4 h-4 text-green-500" />
                        ) : (
                          <TrendingDown className="w-4 h-4 text-red-500" />
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <Badge variant="outline" className={`py-0.5 px-2.5 rounded-full text-[11px] font-bold ${report.risk_level === 'Low Risk' ? 'bg-green-50 text-green-700 border-green-200' : report.risk_level === 'Moderate' ? 'bg-yellow-50 text-yellow-700 border-yellow-200' : 'bg-red-50 text-red-700 border-red-200'}`}>
                        {report.risk_level}
                      </Badge>
                    </td>
                    <td className="px-6 py-4 text-muted-foreground">
                      {format(new Date(report.created_at), "MMM d, yyyy • h:mm a")}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex justify-end gap-2">
                        {report.pdf_url ? (
                          <a href={`${process.env.NEXT_PUBLIC_API_URL}${report.pdf_url}`} target="_blank" rel="noopener noreferrer">
                            <Button variant="outline" size="sm" className="rounded-full gap-2 transition-transform active:scale-95 text-blue-600 border-blue-200 hover:bg-blue-50">
                              <Download className="w-3.5 h-3.5" /> Download PDF
                            </Button>
                          </a>
                        ) : (
                          <Button variant="outline" size="sm" disabled className="rounded-full">
                            Processing
                          </Button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </Card>
    </div>
  );
}



