"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BedDouble, Activity, CheckCircle, AlertTriangle, Sparkles } from "lucide-react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { Badge } from "@/components/ui/badge";

export function AnalyticsCards({ kpis, forecast }: any) {
  if (!kpis) return null;

  return (
    <div className="grid gap-6 md:grid-cols-2">
      {/* 50% Left Side - KPI Data Cards */}
      <div className="grid gap-4 grid-cols-2">
        <Card className="bg-white border-border/50 shadow-sm">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-bold text-muted-foreground uppercase tracking-wider">Total Beds</CardTitle>
            <BedDouble className="w-4 h-4 text-blue-500" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-black text-foreground">{kpis.total_beds}</div>
          </CardContent>
        </Card>

        <Card className="bg-white border-border/50 shadow-sm">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-bold text-muted-foreground uppercase tracking-wider">Occupied</CardTitle>
            <Activity className="w-4 h-4 text-orange-500" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-black text-foreground">{kpis.occupied_beds}</div>
          </CardContent>
        </Card>

        <Card className="bg-white border-border/50 shadow-sm">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-bold text-muted-foreground uppercase tracking-wider">Available</CardTitle>
            <CheckCircle className="w-4 h-4 text-green-500" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-black text-foreground">{kpis.available_beds}</div>
          </CardContent>
        </Card>

        <Card className="bg-white border-border/50 shadow-sm">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-bold text-muted-foreground uppercase tracking-wider">Maintenance</CardTitle>
            <AlertTriangle className="w-4 h-4 text-yellow-500" />
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-black text-foreground">{kpis.maintenance_beds + kpis.cleaning_beds}</div>
          </CardContent>
        </Card>
        
        <Card className={`col-span-2 border-border/50 shadow-sm ${kpis.occupancy_percentage >= 90 ? 'bg-red-50' : kpis.occupancy_percentage >= 75 ? 'bg-orange-50' : 'bg-green-50'}`}>
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-bold text-muted-foreground uppercase tracking-wider">Occupancy %</CardTitle>
            <Activity className={`w-4 h-4 ${kpis.occupancy_percentage >= 90 ? 'text-red-500' : kpis.occupancy_percentage >= 75 ? 'text-orange-500' : 'text-green-500'}`} />
          </CardHeader>
          <CardContent>
            <div className={`text-3xl font-black ${kpis.occupancy_percentage >= 90 ? 'text-red-700' : kpis.occupancy_percentage >= 75 ? 'text-orange-700' : 'text-green-700'}`}>
              {kpis.occupancy_percentage}%
            </div>
          </CardContent>
        </Card>
      </div>

      {/* 50% Right Side - Forecast Chart */}
      <Card className="bg-white border-border/50 shadow-sm p-4 h-full flex flex-col">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-sm font-bold text-muted-foreground uppercase tracking-wider">7-Day Occupancy Forecast</h3>
          <Badge variant="outline" className="bg-indigo-50 text-indigo-700 border-indigo-200 text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 gap-1">
            <Sparkles className="w-3 h-3" />
            AI Forecast
          </Badge>
        </div>
        <p className="text-[10px] text-muted-foreground/70 -mt-3 mb-3 italic">Predictions generated by AI based on historical trends</p>
        <div className="flex-1 min-h-[250px]">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={forecast}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
              <XAxis 
                dataKey="date" 
                tickFormatter={(val) => new Date(val).toLocaleDateString('en-US', { weekday: 'short' })}
                axisLine={false}
                tickLine={false}
                tick={{ fontSize: 12, fill: '#6B7280' }}
                dy={10}
              />
              <YAxis 
                axisLine={false}
                tickLine={false}
                tick={{ fontSize: 12, fill: '#6B7280' }}
                dx={-10}
                domain={[0, 100]}
              />
              <Tooltip 
                contentStyle={{ borderRadius: '8px', border: '1px solid #E5E7EB', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }}
                labelFormatter={(val) => new Date(val).toLocaleDateString()}
                formatter={(val: any) => [`${val}%`, 'Occupancy']}
              />
              <Line 
                type="monotone" 
                dataKey="occupancy" 
                stroke="#3b82f6" 
                strokeWidth={3}
                dot={{ r: 4, strokeWidth: 2 }}
                activeDot={{ r: 6 }}
              />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </Card>
    </div>
  );
}
