"""Add updated_at to ResourceRequest

Revision ID: 09cdbc1e7776
Revises: 524469d847c5
Create Date: 2026-08-08 22:43:49.154635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09cdbc1e7776'
down_revision: Union[str, Sequence[str], None] = '524469d847c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_requests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_requests', 'updated_at')
    # ### end Alembic commands ###
