"""Add resource_name to ResourceRequest

Revision ID: 524469d847c5
Revises: f3a9d5f94579
Create Date: 2026-08-08 22:20:07.004735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524469d847c5'
down_revision: Union[str, Sequence[str], None] = 'f3a9d5f94579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_requests', sa.Column('resource_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_requests', 'resource_name')
    # ### end Alembic commands ###
