"""add random attendance checks

Revision ID: 6d95ea3c949c
Revises: 199fb36af7d2
Create Date: 2026-08-08 16:15:56.182351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d95ea3c949c'
down_revision: Union[str, Sequence[str], None] = '199fb36af7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_attendance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['daily_qr_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_random_attendance_checks_doctor_id'), 'random_attendance_checks', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_random_attendance_checks_id'), 'random_attendance_checks', ['id'], unique=False)
    op.create_index(op.f('ix_random_attendance_checks_session_id'), 'random_attendance_checks', ['session_id'], unique=False)
    op.create_index(op.f('ix_random_attendance_checks_status'), 'random_attendance_checks', ['status'], unique=False)
    op.add_column('daily_qr_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('doctors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=False)
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_column('doctors', 'user_id')
    op.drop_column('daily_qr_sessions', 'updated_at')
    op.drop_index(op.f('ix_random_attendance_checks_status'), table_name='random_attendance_checks')
    op.drop_index(op.f('ix_random_attendance_checks_session_id'), table_name='random_attendance_checks')
    op.drop_index(op.f('ix_random_attendance_checks_id'), table_name='random_attendance_checks')
    op.drop_index(op.f('ix_random_attendance_checks_doctor_id'), table_name='random_attendance_checks')
    op.drop_table('random_attendance_checks')
    # ### end Alembic commands ###
