"""Add device location to DailyQRSession

Revision ID: 8c4d2d7cc1fa
Revises: ac0046cd4934
Create Date: 2026-09-08 01:00:57.289920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4d2d7cc1fa'
down_revision: Union[str, Sequence[str], None] = 'ac0046cd4934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_qr_sessions', sa.Column('device_lat', sa.Float(), nullable=True))
    op.add_column('daily_qr_sessions', sa.Column('device_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_qr_sessions', 'device_lng')
    op.drop_column('daily_qr_sessions', 'device_lat')
    # ### end Alembic commands ###
