"""Unified Patient Profile

Revision ID: d1417659ae11
Revises: 6a25ff6990c5
Create Date: 2026-08-23 20:44:38.874771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1417659ae11'
down_revision: Union[str, Sequence[str], None] = '6a25ff6990c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_logs', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_logs_patient_id'), 'inventory_logs', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'inventory_logs', 'patients', ['patient_id'], ['id'])
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=False)
    op.drop_constraint(None, 'inventory_logs', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_logs_patient_id'), table_name='inventory_logs')
    op.drop_column('inventory_logs', 'patient_id')
    # ### end Alembic commands ###
