"""add admin note

Revision ID: f3a9d5f94579
Revises: 6d95ea3c949c
Create Date: 2026-08-08 22:03:07.029199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a9d5f94579'
down_revision: Union[str, Sequence[str], None] = '6d95ea3c949c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_requests', sa.Column('admin_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_requests', 'admin_note')
    # ### end Alembic commands ###
